-- schema.sql is deprecated: tests now use Postgres Testcontainers (jdbc:tc:postgresql...) and Flyway migrations from src/main/resources/db/migration
-- Kept for historical reference; not used by current test profile
